name: Simple Workflow

on:
  push:
  pull_request:
  workflow_dispatch:   # allows manual trigger from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ The workflow is running!"
